export default {

    // Storage actions
    UPDATE_DEVICE_LIST: 'UPDATE_DEVICE_LIST',
    SELECT_DEVICE: 'SELECT_DEVICE',
    SYNC_STORAGE: 'SYNC_STORAGE',
    PUSH_ROUTE: 'PUSH_ROUTE',

    // Storage mutations
    SET_DEVICE_LIST: 'SET_DEVICE_LIST',
    SET_DEVICE_SELECTED: 'SET_DEVICE_SELECTED',
    SET_VALUES_FROM_STORAGE: 'SET_VALUES_FROM_STORAGE',
    SET_LAST_ROUTE: 'SET_LAST_ROUTE',
    SET_INITIALIZED: 'SET_INITIALIZED'
};